# Generated by Django 5.1 on 2024-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(upload_to="File/"),
        ),
        migrations.AlterField(
            model_name="myimage",
            name="image",
            field=models.ImageField(upload_to="MyImages/"),
        ),
    ]
