# Generated by Django 5.1 on 2024-12-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("content", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="certification_categories",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="certification_link",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.CharField()),
                (
                    "categories_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="about.certification_categories",
                    ),
                ),
            ],
        ),
    ]
