# Generated by Django 5.1 on 2024-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_achievements_certification_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification_link",
            name="content",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
