# Generated by Django 5.1 on 2024-12-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_certification_link_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification_link",
            name="title",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="certification_link",
            name="content",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="certification_link",
            name="link",
            field=models.CharField(max_length=500),
        ),
    ]
