# Generated by Django 5.1 on 2024-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_work_experience_and_internships"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification_link",
            name="categories_id",
        ),
        migrations.AddField(
            model_name="certification_link",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="certification_link",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="certification_categories",
        ),
    ]
