# Generated by Django 5.1 on 2024-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="see_my_work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("github_link", models.URLField(max_length=300)),
                ("website_link", models.URLField(max_length=300)),
            ],
        ),
    ]
