# Generated by Django 5.1 on 2024-12-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Skill", "0002_see_my_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="see_my_work",
            name="work",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="see_my_works",
                to="Skill.workmodel",
            ),
            preserve_default=False,
        ),
    ]
